config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :articles
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
 def index
    @articles = Article.all
  end

  def show
    @article = Article.find(params[:id])
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    @article.save
    redirect_to articles_path(@article)
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])
    @article.update(article_params)
    redirect_to articles_path(@article)
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy
    redirect_to articles_path
  end

  private

  def article_params
    params.require(:article).permit(:title, :content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/edit.html.erb
<%= form_for(@article) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :content %>
  <%= f.text_field :content %>
  <%= f.submit %>
<% end %>

<%= link_to 'Back', articles_path %>
<%= link_to 'Show', article_path %>

app/views/articles/index.html.erb
<% @articles.each do |article| %>
<li><%= link_to article.title, article_path(article) %> </li>
<p><%= article.content %></p>
<% end %>

<%= link_to "New article", new_article_path %>
<%= link_to "Wikinimous", articles_path %>

app/views/articles/new.html.erb
<%= form_for(@article) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :content%>
  <%= f.text_field :content %>
  <%= f.submit %>
<% end %>

<%= link_to 'Wikiminous', tasks_path %>
<%= link_to "New article", new_article_path %>

app/views/articles/show.html.erb
<h1><%= @article.title %></h1>
<p><%= @article.content %></p>

<%= link_to 'Wikiminous', articles_path %>
<%= link_to 'Edit the task', edit_article_path(@article) %>
<%= link_to "New article", new_article_path %>
<%= link_to "Delete #{@article.title}", article_path(@article), method: :delete, data: {confirm: 'Do you really want to?'} %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWikinimous</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>